"""Content credentials: what the file claims about its own origin.

The parsing tests run on manifest dictionaries rather than on signed files, so they
work in CI without shipping a certificate or a 2 MB fixture. The end-to-end test
needs a genuinely signed image and skips when there is not one to hand.

The behaviour worth protecting is the asymmetry. A valid manifest saying "generated"
is close to conclusive, and the absence of any manifest means nothing at all, because
one re-save removes it. If absence ever starts reading as innocence, every honest
photograph that passed through a messaging app becomes indistinguishable from a
stripped generated one, in the wrong direction.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from groundtruth.core.types import ImageCase, Tier
from groundtruth.detectors.provenance.content_credentials import (
    _IPTC,
    _software,
    _source_types,
)

pytest.importorskip("c2pa", reason="needs the [provenance] extra")

from groundtruth.core.detector import get

DETECTOR = "provenance.content_credentials"

# A real OpenAI export, if one happens to be around. Not committed: it is 2 MB and
# byte-fragile, since re-saving it to shrink it would strip the very chunk under test.
SIGNED = Path.home() / "Downloads" / "ChatGPT Image Jul 2, 2026, 08_05_09 PM.png"


def _manifest(source_type: str | None = None, agent: str | None = None) -> dict:
    action: dict = {"action": "c2pa.created"}
    if source_type:
        action["digitalSourceType"] = _IPTC + source_type
    if agent:
        action["softwareAgent"] = {"name": agent}
    return {"assertions": [{"label": "c2pa.actions.v2", "data": {"actions": [action]}}]}


# --------------------------------------------------------------------------
# Reading a manifest
# --------------------------------------------------------------------------


def test_source_type_is_read_from_the_action():
    assert _source_types(_manifest("trainedAlgorithmicMedia")) == ["trainedAlgorithmicMedia"]


def test_full_iptc_uri_is_reduced_to_its_meaningful_suffix():
    """The vocabulary is a URI. Only the last segment carries the meaning, and
    matching on the whole string would break if IPTC moved the prefix."""
    long = _manifest("digitalCapture")
    assert _source_types(long) == ["digitalCapture"]


def test_missing_source_type_yields_nothing_rather_than_raising():
    assert _source_types(_manifest()) == []
    assert _source_types({}) == []


def test_software_agent_is_read_from_either_shape():
    assert _software(_manifest(agent="gpt-image")) == "gpt-image"
    flat = {"assertions": [{"data": {"actions": [{"softwareAgent": "Photoshop"}]}}]}
    assert _software(flat) == "Photoshop"
    assert _software({"claim_generator": "Some Tool/1.0"}) == "Some Tool/1.0"


# --------------------------------------------------------------------------
# The detector's asymmetry
# --------------------------------------------------------------------------


def test_a_file_without_credentials_abstains_rather_than_clearing(tmp_path):
    """The load-bearing test. Absence must never read as authenticity."""
    from PIL import Image

    p = tmp_path / "plain.jpg"
    Image.new("RGB", (64, 64), (128, 128, 128)).save(p)
    ev = get(DETECTOR).run(ImageCase(image_path=p))
    assert ev.applicable is False
    assert ev.confidence == 0.0
    assert "no content credentials" in ev.explanation


def test_detector_is_registered_in_its_own_tier():
    det = get(DETECTOR)
    assert det.tier is Tier.PROVENANCE
    assert det.localises is False


def test_it_runs_before_the_expensive_tiers():
    """Reading a metadata chunk costs nothing next to torch inference, and a
    conclusive answer from it should not wait behind eight seconds of pixel work."""
    from groundtruth.core.detector import all_detectors

    costs = {d.id: d.cost for d in all_detectors()}
    assert costs[DETECTOR] <= min(
        c for i, c in costs.items() if i.startswith("sensor.")
    )


# --------------------------------------------------------------------------
# End to end, on a genuinely signed file
# --------------------------------------------------------------------------


@pytest.mark.skipif(not SIGNED.is_file(), reason="no signed sample available")
def test_a_signed_ai_image_is_flagged_with_its_generator_named():
    ev = get(DETECTOR).run(ImageCase(image_path=SIGNED))
    assert ev.applicable
    assert ev.score > 0.9, "a signed generative claim should be near-conclusive"
    assert ev.confidence > 0.9
    assert "generated by an AI model" in ev.explanation
    assert ev.details["validation_state"].lower() == "valid"
    assert "trainedAlgorithmicMedia" in ev.details["digital_source_types"]


@pytest.mark.skipif(not SIGNED.is_file(), reason="no signed sample available")
def test_the_whole_pipeline_flags_what_it_used_to_clear():
    """Before this tier existed, a real ChatGPT export was cleared at 0.288, which
    was lower than a genuine untouched photograph. That is the regression."""
    from groundtruth.core.types import Decision
    from groundtruth.pipeline.runner import analyse

    verdict = analyse(ImageCase(image_path=SIGNED))
    assert verdict.decision is Decision.FLAG
    assert verdict.manipulated_probability > 0.8


@pytest.mark.skipif(not SIGNED.is_file(), reason="no signed sample available")
def test_credentials_do_not_survive_a_re_save(tmp_path):
    """The limit, asserted rather than described. Re-saving the file strips the
    manifest, and the detector must then abstain instead of remembering."""
    from PIL import Image

    stripped = tmp_path / "resaved.png"
    Image.open(SIGNED).convert("RGB").save(stripped)
    assert get(DETECTOR).run(ImageCase(image_path=stripped)).applicable is False
