"""What the file says about its own origin, and whether that claim is signed.

Every other detector in this project asks whether a photograph was altered after
capture. That question presumes a capture. An image generated end to end was never
captured: there is no region that disagrees with its surroundings, because the whole
frame was synthesised at once, so the sensor and geometric tiers abstain and the
fused verdict is `AUTO_CLEAR`. Measured on a real ChatGPT export, 0.288, which is
lower than a genuine untouched photograph scored on the same pipeline.

The answer turned out to be in the file rather than in the pixels. That export
carries a 29 KB `caBX` chunk: a C2PA manifest, signed by OpenAI, asserting
`digitalSourceType: trainedAlgorithmicMedia`. The image declares that it was
generated, and the pipeline was reading past it to look for demosaicing artefacts
that were never going to be there.

**This is a different evidential standard to the rest of the metadata tier.** An
EXIF timestamp is a string anyone can type. A C2PA manifest is signed against a
certificate chain, so it either verifies or it does not, and a manifest that has
been edited fails verification rather than lying convincingly. That is why this
reports at high confidence where `metadata.container_identity` reports at 0.25.

**And it is deliberately asymmetric.** A valid manifest saying "generated" is close
to conclusive. The absence of any manifest means nothing at all, because credentials
are trivially stripped: screenshot the image, re-save it, or send it through almost
any social platform and the chunk is gone. So the detector abstains on absence
rather than treating it as evidence of authenticity, which is the same rule the
fusion already applies to every other tier. `scripts/sweep_credentials.py` measures
how easily the manifest is removed, so that limit is a number rather than a caveat.
"""

from __future__ import annotations

from ...core.detector import Detector, register
from ...core.types import Evidence, ImageCase, Tier

# IPTC digital source type vocabulary, the field C2PA uses to say how an image came
# to exist. The full URIs are long and the suffix is the part that carries meaning.
_IPTC = "http://cv.iptc.org/newscodes/digitalsourcetype/"

# Suffixes that mean a model produced the pixels, wholly or in part.
_SYNTHETIC = {
    "trainedAlgorithmicMedia": "generated by an AI model",
    "compositeWithTrainedAlgorithmicMedia": "partly generated by an AI model",
    "algorithmicMedia": "produced algorithmically rather than photographed",
}

# Suffixes that mean a lens and a sensor were involved.
_CAPTURED = {
    "digitalCapture": "captured by a camera",
    "negativeFilm": "scanned from film",
    "positiveFilm": "scanned from film",
    "print": "scanned from a print",
}


def _source_types(manifest: dict) -> list[str]:
    """Every digitalSourceType asserted anywhere in the active manifest."""
    found: list[str] = []
    for assertion in manifest.get("assertions", []) or []:
        data = assertion.get("data") or {}
        for action in data.get("actions") or []:
            uri = action.get("digitalSourceType")
            if uri:
                found.append(str(uri).rsplit("/", 1)[-1])
        uri = data.get("digitalSourceType")
        if uri:
            found.append(str(uri).rsplit("/", 1)[-1])
    return found


def _software(manifest: dict) -> str | None:
    """The tool that made the claim, however this generator chose to record it."""
    for assertion in manifest.get("assertions", []) or []:
        for action in (assertion.get("data") or {}).get("actions") or []:
            agent = action.get("softwareAgent")
            if isinstance(agent, dict) and agent.get("name"):
                return str(agent["name"])
            if isinstance(agent, str) and agent:
                return agent
    gen = manifest.get("claim_generator_info") or []
    if gen and isinstance(gen, list) and gen[0].get("name"):
        return str(gen[0]["name"])
    return manifest.get("claim_generator") or None


@register
class ContentCredentialsDetector(Detector):
    """Read and verify C2PA Content Credentials, if the file carries any."""

    id = "provenance.content_credentials"
    tier = Tier.PROVENANCE
    localises = False
    cost = 1

    def applies_to(self, case: ImageCase) -> tuple[bool, str]:
        try:
            import c2pa  # noqa: F401
        except ImportError:
            return False, "reading content credentials requires the c2pa extra"
        return True, ""

    def _run(self, case: ImageCase) -> Evidence:
        from c2pa import Reader

        try:
            with Reader(str(case.image_path)) as reader:
                import json

                report = json.loads(reader.json())
        except Exception:
            # No manifest is by far the most common case and is not an error worth
            # surfacing. A malformed one lands here too, and the honest reading of
            # both is the same: this file tells us nothing about where it came from.
            return Evidence.not_applicable(
                self.id, self.tier, "this file carries no content credentials"
            )

        active = (report.get("manifests") or {}).get(report.get("active_manifest"))
        if not active:
            return Evidence.not_applicable(
                self.id, self.tier, "this file carries no content credentials"
            )

        state = str(report.get("validation_state", "")).lower()
        signer = (active.get("signature_info") or {}).get("issuer")
        tool = _software(active)
        sources = _source_types(active)
        details: dict[str, object] = {
            "validation_state": report.get("validation_state"),
            "issuer": signer,
            "software_agent": tool,
            "digital_source_types": sources,
            "signed_at": (active.get("signature_info") or {}).get("time"),
        }

        # A manifest that fails verification has been altered since signing, which is
        # a finding in itself: someone edited a file that was carrying a signature.
        if state and state != "valid":
            return Evidence(
                detector_id=self.id, tier=self.tier, applicable=True,
                score=0.80, confidence=0.75, effect_size=0.7,
                explanation=(
                    "this file carries content credentials that do not verify, so it "
                    "has been altered since it was signed"
                ),
                details=details,
            )

        synthetic = [s for s in sources if s in _SYNTHETIC]
        if synthetic:
            how = _SYNTHETIC[synthetic[0]]
            by = f" by {tool}" if tool else ""
            issued = f", signed by {signer}" if signer else ""
            return Evidence(
                detector_id=self.id, tier=self.tier, applicable=True,
                # Not 1.0. The signature proves the file says this about itself and
                # that nobody has altered it since, which is a strong claim and not
                # the same as a physical measurement of the pixels.
                score=0.97, confidence=0.95, effect_size=1.0,
                explanation=(
                    f"this image says it was {how}{by}, and the claim is "
                    f"cryptographically signed{issued}"
                ),
                details=details,
            )

        captured = [s for s in sources if s in _CAPTURED]
        if captured:
            issued = f" by {signer}" if signer else ""
            return Evidence(
                detector_id=self.id, tier=self.tier, applicable=True,
                # Below 0.5, so this is positive evidence of authenticity. Almost
                # nothing else in the pipeline can produce that: every other detector
                # can only fail to find a problem.
                score=0.10, confidence=0.80, effect_size=0.6,
                explanation=(
                    f"this image carries a signed record{issued} that it was "
                    f"{_CAPTURED[captured[0]]}"
                ),
                details=details,
            )

        # Signed, verified, but silent on how the pixels were made. Worth reporting,
        # because a valid chain still tells a reviewer who handled the file.
        return Evidence(
            detector_id=self.id, tier=self.tier, applicable=True,
            score=0.45, confidence=0.30, effect_size=0.2,
            explanation=(
                "this file carries valid content credentials, but they do not say "
                "whether it was photographed or generated"
            ),
            details=details,
        )
